pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["asientos_contables.htm","Importación &#62; Asientos Contables","Asientos Contables",""],
["expediente.htm","Importación &#62; Expediente","Expediente",""],
["gastos_estimados_indirectos.htm","Importación &#62; Gastos Estimados e Indirectos","Gastos Estimados e Indirectos",""],
["importacion.htm","Importación","Importación",""],
["importaciones_libro_impuestos.htm","Importación &#62; Importaciones en Libro de Compras y Ventas","Importaciones en Libro de Impuestos",""],
["otras_consideraciones.htm","Importación &#62; Otras Consideraciones","Otras Consideraciones",""],
["proceso_de_importacion.htm","Importación &#62; Proceso de Importación","Proceso de Importación",""],
["recepcion.htm","Importación &#62; Recepción","Recepción",""],
["tablas_basicas.htm","Importación &#62; Tablas Básicas","Tablas Básicas",""],
["tipo_persona.htm","Importación &#62; Tipo de Persona","Tipo de Persona",""]];
